swiftmailer:
   url: '%env(MAILER_URL)%'
   spool: { type: 'memory' }
#  transport: smtp
#  auth_mode: login
#  port: 465
#  host: smtp.gmail.com
#  username: stephendupre64@gmail.com
#  password: 64val500
#  spool: { type: 'memory' }
